apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApi1
  template:
    metadata:
      labels:
        app: WebApi1
    spec:
      containers:
      - name: dockersamplerepos
        image: samplesregcr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconsn

---
apiVersion: v1
kind: Service
metadata:
  name: dockersampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApi1